@extends('layouts.front-template')
@section('content')
    @include('front.sections.hero-area')
    @include('front.sections.sticker-pack')
    @include('front.sections.awesome-features')
    @include('front.sections.how-to-make')
    @include('front.sections.graphics-designer')
    @include('front.sections.contact-us')
@endsection
